############################################################################
#
# Makefile for ytree
#
############################################################################

# -------------------------------------------------------------------------
# Directory Configuration
# -------------------------------------------------------------------------
SRC_DIR     = src
INC_DIR     = include
OBJ_DIR     = obj
DOC_DIR     = doc
BUILD_DIR   = build
BIN_DIR     = .

# -------------------------------------------------------------------------
# Toolchain & Utilities
# -------------------------------------------------------------------------
CC          ?= cc
PANDOC      ?= pandoc

# -------------------------------------------------------------------------
# Install Destinations
# -------------------------------------------------------------------------
DESTDIR     = /usr
BINDEST     = $(DESTDIR)/bin
MANDEST     = $(DESTDIR)/share/man/man1

# -------------------------------------------------------------------------
# Compile Options
# -------------------------------------------------------------------------

# ADD_CFLAGS: Add -DVI_KEYS if you want vi-cursor-keys (hjkl navigation)
#
# VI KEYS FEATURE:
#   When enabled, the following keys navigate like vi/vim:
#     h = LEFT,  j = DOWN,  k = UP,  l = RIGHT
#     Ctrl+D = PAGE DOWN,  Ctrl+U = PAGE UP
#
# IMPORTANT: VI keys are DISABLED by default to allow case-insensitive
# key bindings (e.g., both 'k' and 'K' open volume menu).
#
# To enable VI keys, uncomment the line below:
# ADD_CFLAGS  = -DVI_KEYS
#
# Default: VI keys OFF (case-insensitive bindings enabled)
ADD_CFLAGS  =

# Default configuration for Linux (WSL/Ubuntu) with ncurses 6
# NOTE: This build now requires libarchive.
# On Debian/Ubuntu, install with: sudo apt-get install libarchive-dev
COLOR       = -DCOLOR_SUPPORT
CLOCK       = -DCLOCK_SUPPORT
READLINE    = -DREADLINE_SUPPORT

# Compiler Warnings (Scrupulous Mode)
# -Wall -Wextra: Enable most warnings
# -Wno-unused-parameter: Reduce noise from legacy callback signatures
# Note: -Werror=conflicting-types removed for compatibility with older compilers
WARNINGS    = -Wall -Wextra -Wno-unused-parameter

# Standard Flags
# -I$(INC_DIR): Look for headers in the include/ directory
# -MMD -MP:     Auto-generate dependency files (.d) to track header changes
CFLAGS      += -D_GNU_SOURCE -DHAVE_LIBARCHIVE -DWITH_UTF8 \
               $(COLOR) $(CLOCK) $(READLINE) $(ADD_CFLAGS) \
               -I$(INC_DIR) -MMD -MP $(WARNINGS)

LDFLAGS     += -lncursesw -ltinfo -lreadline -larchive -lm

# -------------------------------------------------------------------------
# Build Mode Selection
# Run 'make DEBUG=1' for development (AddressSanitizer enabled)
# Run 'make' for release (Optimized, no runtime dependency on ASan)
# -------------------------------------------------------------------------
ifdef DEBUG
    # Debug Build: Enable ASan, Debug Symbols, disable optimization
    CFLAGS  += -fsanitize=address -g -O1 -fno-omit-frame-pointer
    LDFLAGS += -fsanitize=address
else
    # Release Build: Standard Optimization
    CFLAGS  += -O2
endif

# -------------------------------------------------------------------------
# Files
# -------------------------------------------------------------------------
MAIN        = ytree
MAIN_BIN    = $(BUILD_DIR)/$(MAIN)
MANSRC      = $(DOC_DIR)/ytree.1.md
MANPAGE     = $(BUILD_DIR)/ytree.1

# Automatically find all .c files in src/ and subdirectories
SRCS        = $(wildcard $(SRC_DIR)/*.c $(SRC_DIR)/*/*.c)
# Generate object filenames in obj/
OBJS        = $(patsubst $(SRC_DIR)/%.c, $(OBJ_DIR)/%.o, $(SRCS))
# Dependency files generated by compiler
DEPS        = $(OBJS:.o=.d)

# -------------------------------------------------------------------------
# Rules
# -------------------------------------------------------------------------

.PHONY: all clean clobber install uninstall docs changelog-draft test test-v

all: $(MAIN_BIN) $(MANPAGE)

# Link the executable
$(MAIN_BIN): $(OBJS) | $(BUILD_DIR)
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LDFLAGS)

# Compile source files into object files
# Ensure the specific subdirectory exists in obj/ before compiling
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# Create the build directory
$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

# Generate USAGE.md from the man page source
docs:
	$(PANDOC) -f markdown-tex_math_dollars -t gfm \
		--metadata title="Ytree Usage" \
		$(MANSRC) -o $(DOC_DIR)/USAGE.md

# Generate the roff man page
$(MANPAGE): $(MANSRC) | $(BUILD_DIR)
	$(PANDOC) -s -t man $(MANSRC) -o $@

# Install binary and man page
install: $(MAIN_BIN) $(MANPAGE) docs
	if [ ! -e $(BINDEST) ]; then mkdir -p $(BINDEST); fi
	install $(MAIN_BIN) $(BINDEST)/$(MAIN)
	if [ ! -e $(MANDEST) ]; then mkdir -p $(MANDEST); fi
	gzip -9c $(MANPAGE) > $(MANPAGE).gz
	install -m 0644 $(MANPAGE).gz $(MANDEST)/
	rm $(MANPAGE).gz

# Uninstall
uninstall:
	rm -f $(BINDEST)/$(MAIN)
	rm -f $(MANDEST)/ytree.1.gz

# Draft Changelog generator
# If no tags exist, uses the full history (HEAD).
changelog-draft:
	@echo "### Added"
	@RANGE=$$(git describe --tags --abbrev=0 2>/dev/null); \
	if [ -z "$$RANGE" ]; then RANGE="HEAD"; else RANGE="$$RANGE..HEAD"; fi; \
	git log $$RANGE --grep="^feat" --pretty=format:"- %s"
	@echo "\n\n### Fixed"
	@RANGE=$$(git describe --tags --abbrev=0 2>/dev/null); \
	if [ -z "$$RANGE" ]; then RANGE="HEAD"; else RANGE="$$RANGE..HEAD"; fi; \
	git log $$RANGE --grep="^fix" --pretty=format:"- %s"
	@echo "\n\n### Other"
	@RANGE=$$(git describe --tags --abbrev=0 2>/dev/null); \
	if [ -z "$$RANGE" ]; then RANGE="HEAD"; else RANGE="$$RANGE..HEAD"; fi; \
	git log $$RANGE --grep="^refactor\|^chore" --pretty=format:"- %s"
	@echo ""

# Clean build artifacts
clean:
	rm -rf $(OBJ_DIR) $(BUILD_DIR)
	rm -f core *~ *.orig *.bak
	find $(SRC_DIR) -name "*.o" -o -name "*.d" -delete

clobber: clean
	rm -f $(MAIN) # Just in case legacy binary exists

mrproper: clobber
	rm -rf $(OBJ_DIR) $(BUILD_DIR)
	find . -name "*.o" -o -name "*.d" -delete

# Include automatically generated dependencies
-include $(DEPS)

# Test Targets
PYTEST ?= $(shell if [ -x .venv/bin/pytest ]; then echo ".venv/bin/pytest"; else echo "pytest"; fi)

test: $(MAIN_BIN)
	$(PYTEST)

test-v: $(MAIN_BIN)
	$(PYTEST) -v -s