############################################################################
#
# Makefile for ytree
#
############################################################################

# -------------------------------------------------------------------------
# Version Information
# -------------------------------------------------------------------------
VERSION     = 3.0.0-alpha
VERSIONDATE = April 2026

# -------------------------------------------------------------------------
# Directory Configuration
# -------------------------------------------------------------------------
SRC_DIR     = src
INC_DIR     = include
OBJ_DIR     = obj
DOC_DIR     = doc
BUILD_DIR   = build
BIN_DIR     = .

# -------------------------------------------------------------------------
# Toolchain & Utilities
# -------------------------------------------------------------------------
CC          ?= cc
PANDOC      ?= pandoc
MAKE_CMD    ?= $(MAKE)

# -------------------------------------------------------------------------
# Install Destinations
# -------------------------------------------------------------------------
PREFIX      ?= /usr/local
DESTDIR     ?=
BINDIR      = $(PREFIX)/bin
MANDIR      = $(PREFIX)/share/man
MAN1DIR     = $(MANDIR)/man1

# For compatibility with old variable names
BINDEST     = $(DESTDIR)$(BINDIR)
MANDEST     = $(DESTDIR)$(MAN1DIR)

# -------------------------------------------------------------------------
# Compile Options
# -------------------------------------------------------------------------

# Optional extra compiler flags (for local experiments/debugging).
ADD_CFLAGS  =

# Default configuration for Linux (WSL/Ubuntu) with ncurses 6
# NOTE: This build now requires libarchive.
# On Debian/Ubuntu, install with: sudo apt-get install libarchive-dev
COLOR       = -DCOLOR_SUPPORT
CLOCK       = -DCLOCK_SUPPORT
READLINE    = -DREADLINE_SUPPORT

# Compiler Warnings (Scrupulous Mode)
# -Wall -Wextra: Enable most warnings
# -Wno-unused-parameter: Reduce noise from legacy callback signatures
# Note: -Werror=conflicting-types removed for compatibility with older compilers
WARNINGS    = -Wall -Wextra -Wno-unused-parameter

# Standard Flags
# -I$(INC_DIR): Look for headers in the include/ directory
# -MMD -MP:     Auto-generate dependency files (.d) to track header changes
# -DVERSION, -DVERSIONDATE: Version info from Makefile variables
CFLAGS      += -D_GNU_SOURCE -DHAVE_LIBARCHIVE -DWITH_UTF8 \
               -DVERSION='"$(VERSION)"' -DVERSIONDATE='"$(VERSIONDATE)"' \
               $(COLOR) $(CLOCK) $(READLINE) $(ADD_CFLAGS) \
               -I$(INC_DIR) -MMD -MP $(WARNINGS)

LDFLAGS     += -lncursesw -ltinfo -lreadline -larchive -lm

# -------------------------------------------------------------------------
# Build Mode Selection
# Run 'make DEBUG=1' for development (AddressSanitizer enabled)
# Run 'make' for release (Optimized, no runtime dependency on ASan)
# -------------------------------------------------------------------------
ifeq ($(DEBUG),1)
    # Debug Build: Enable ASan, Debug Symbols, disable optimization
    CFLAGS  += -fsanitize=address -g -O1 -fno-omit-frame-pointer
    LDFLAGS += -fsanitize=address
else
    # Release Build: Standard Optimization
    CFLAGS  += -O2
endif

# -------------------------------------------------------------------------
# Files
# -------------------------------------------------------------------------
MAIN        = ytree
MAIN_BIN    = $(BUILD_DIR)/$(MAIN)
MANSRC      = etc/ytree.1.md
MANPAGE     = $(BUILD_DIR)/ytree.1

# Automatically find all .c files in src/ and subdirectories
SRCS        = $(wildcard $(SRC_DIR)/*.c $(SRC_DIR)/*/*.c)
# Generate object filenames in obj/
OBJS        = $(patsubst $(SRC_DIR)/%.c, $(OBJ_DIR)/%.o, $(SRCS))
# Dependency files generated by compiler
DEPS        = $(OBJS:.o=.d)
CLANG_TIDY_SRCS = $(shell find $(SRC_DIR) -name '*.c' -type f)

# -------------------------------------------------------------------------
# QA Defaults
# -------------------------------------------------------------------------
# Set QA_ON_BUILD=1 to run full QA (including pytest) after a normal build:
#   make QA_ON_BUILD=1
QA_ON_BUILD ?= 0
QA_LOG ?= qa-all.log

# -------------------------------------------------------------------------
# Rules
# -------------------------------------------------------------------------

.PHONY: all clean clobber install uninstall docs changelog-draft hooks-install hooks-status \
	git-aliases-install git-aliases-status test \
	test-v qa-clang qa-cppcheck qa-scan qa-valgrind qa-valgrind-interactive qa-valgrind-full \
	qa-pytest qa-unsafe-apis qa-module-boundaries qa-ai-config qa-all mcp-doctor \
	qa-all-log

all: $(MAIN_BIN) $(MANPAGE) $(if $(filter 1,$(QA_ON_BUILD)),qa-all)

# Link the executable
$(MAIN_BIN): $(OBJS) | $(BUILD_DIR)
	$(CC) $(CFLAGS) -o $@ $(OBJS) $(LDFLAGS)

# Compile source files into object files
# Ensure the specific subdirectory exists in obj/ before compiling
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# Create the build directory
$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

# Generate USAGE.md from the man page source
docs:
	$(PANDOC) -f markdown-tex_math_dollars -t gfm \
		--metadata title="Ytree Usage" \
		$(MANSRC) -o $(DOC_DIR)/USAGE.md

# Generate the roff man page
$(MANPAGE): $(MANSRC) | $(BUILD_DIR)
	$(PANDOC) -s -t man $(MANSRC) -o $@

# Install binary, man page, and documentation
install: $(MAIN_BIN) $(MANPAGE) docs
	@echo "Installing ytree $(VERSION) to $(PREFIX)..."
	install -d -m 755 $(BINDEST)
	install -m 755 $(MAIN_BIN) $(BINDEST)/$(MAIN)
	install -d -m 755 $(MANDEST)
	gzip -9c $(MANPAGE) > $(MANPAGE).gz
	install -m 644 $(MANPAGE).gz $(MANDEST)/$(MAIN).1.gz
	rm -f $(MANPAGE).gz
	@echo "Installation complete."
	@echo "Binary: $(BINDEST)/$(MAIN)"
	@echo "Manual: $(MANDEST)/$(MAIN).1.gz"

# Uninstall all installed files
uninstall:
	@echo "Uninstalling ytree from $(PREFIX)..."
	rm -f $(BINDEST)/$(MAIN)
	rm -f $(MANDEST)/$(MAIN).1.gz
	-rmdir $(MANDEST) 2>/dev/null || true
	-rmdir $(MANDIR) 2>/dev/null || true
	-rmdir $(BINDEST) 2>/dev/null || true
	-rmdir $(PREFIX)/share 2>/dev/null || true
	-rmdir $(PREFIX) 2>/dev/null || true
	@echo "Uninstall complete."

# Draft Changelog generator
# If no tags exist, uses the full history (HEAD).
changelog-draft:
	@echo "### Added"
	@RANGE=$$(git describe --tags --abbrev=0 2>/dev/null); \
	if [ -z "$$RANGE" ]; then RANGE="HEAD"; else RANGE="$$RANGE..HEAD"; fi; \
	git log $$RANGE --grep="^feat" --pretty=format:"- %s"
	@echo "\n\n### Fixed"
	@RANGE=$$(git describe --tags --abbrev=0 2>/dev/null); \
	if [ -z "$$RANGE" ]; then RANGE="HEAD"; else RANGE="$$RANGE..HEAD"; fi; \
	git log $$RANGE --grep="^fix" --pretty=format:"- %s"
	@echo "\n\n### Other"
	@RANGE=$$(git describe --tags --abbrev=0 2>/dev/null); \
	if [ -z "$$RANGE" ]; then RANGE="HEAD"; else RANGE="$$RANGE..HEAD"; fi; \
	git log $$RANGE --grep="^refactor\|^chore" --pretty=format:"- %s"
	@echo ""

hooks-install:
	git config core.hooksPath .githooks
	$(MAKE_CMD) git-aliases-install
	chmod +x .githooks/pre-push
	@echo "Git hooks installed from .githooks/ (core.hooksPath=.githooks)."
	@echo "Git aliases installed: push-fast, push-fast-up"

hooks-status:
	@echo "core.hooksPath=$$(git config --get core.hooksPath || echo .git/hooks)"
	$(MAKE_CMD) git-aliases-status

git-aliases-install:
	git config --local alias.push-fast '!f(){ YTREE_PRE_PUSH_FAST=1 git push "$$@"; }; f'
	git config --local alias.push-fast-up '!f(){ branch=$$(git rev-parse --abbrev-ref HEAD); YTREE_PRE_PUSH_FAST=1 git push -u origin "$$branch" "$$@"; }; f'

git-aliases-status:
	@echo "alias.push-fast=$$(git config --local --get alias.push-fast || echo '<not set>')"
	@echo "alias.push-fast-up=$$(git config --local --get alias.push-fast-up || echo '<not set>')"

# Clean build artifacts
clean:
	rm -rf $(OBJ_DIR) $(BUILD_DIR)
	rm -f core *~ *.orig *.bak
	find $(SRC_DIR) -name "*.o" -o -name "*.d" -delete

clobber: clean
	rm -f $(MAIN) # Just in case legacy binary exists

mrproper: clobber
	rm -rf $(OBJ_DIR) $(BUILD_DIR)
	find . -name "*.o" -o -name "*.d" -delete

# Include automatically generated dependencies
-include $(DEPS)

# Test Targets
PYTEST ?= $(shell if [ -x .venv/bin/pytest ]; then echo ".venv/bin/pytest"; else echo "pytest"; fi)

test: $(MAIN_BIN)
	$(PYTEST)

test-v: $(MAIN_BIN)
	$(PYTEST) -v -s

# QA Targets
qa-clang:
	$(MAKE_CMD) QA_ON_BUILD=0 clean
	bear -- $(MAKE_CMD) QA_ON_BUILD=0 all
	clang-tidy $(CLANG_TIDY_SRCS) -p .

qa-cppcheck:
	cppcheck --enable=all --inconclusive --force --std=c99 -I include --error-exitcode=1 --suppressions-list=.cppcheck-suppressions.txt src include

qa-scan:
	$(MAKE_CMD) QA_ON_BUILD=0 clean
	scan-build --status-bugs $(MAKE_CMD) QA_ON_BUILD=0 all

qa-valgrind:
	$(MAKE_CMD) QA_ON_BUILD=0 clean
	$(MAKE_CMD) QA_ON_BUILD=0 all
	@echo "Running non-interactive valgrind smoke check (output in valgrind.log)."
	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 --log-file=valgrind.log ./build/ytree --version >/dev/null

qa-valgrind-interactive:
	$(MAKE_CMD) QA_ON_BUILD=0 clean
	$(MAKE_CMD) QA_ON_BUILD=0 all
	@echo "Interactive valgrind run: exit ytree cleanly to finish."
	valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 --log-file=valgrind.log ./build/ytree .

qa-valgrind-full:
	$(MAKE_CMD) DEBUG=0 QA_ON_BUILD=0 clean
	$(MAKE_CMD) DEBUG=0 QA_ON_BUILD=0 all
	@echo "Running automated interactive valgrind session (output in valgrind.log)."
	.venv/bin/python scripts/valgrind_session.py

qa-pytest: $(MAIN_BIN)
	TERM=$${TERM:-xterm} $(PYTEST)

qa-unsafe-apis:
	python3 scripts/check_c_unsafe_apis.py

qa-module-boundaries:
	python3 scripts/check_module_boundaries.py

qa-ai-config:
	python3 scripts/check_project_ai_config.py

qa-all: qa-clang qa-cppcheck qa-scan qa-valgrind qa-pytest qa-unsafe-apis qa-module-boundaries qa-ai-config

qa-all-log:
	@mkdir -p "$(dir $(QA_LOG))"
	/bin/bash -o pipefail -c '$(MAKE_CMD) qa-all 2>&1 | tee "$(QA_LOG)"'

mcp-doctor:
	python3 scripts/mcp_doctor.py $(if $(filter 1,$(FIX)),--fix,)
