/* Auto-generated from packaged preset sources under etc/commands/. */
typedef struct {
  const char *preset_id;
  const char *contents;
} DefaultCommandPresetCatalogEntry;

static const DefaultCommandPresetCatalogEntry default_command_presets_catalog[] = {
    {"de",
        "# Alternative YtreeNova command layout: de\n"
        "#\n"
        "# This file defines the named \"de\" command preset.\n"
        "# It is an alternative to the default layout in etc/ytnova.commands.\n"
        "#\n"
        "# YtreeNova uses this file only if the user selects:\n"
        "#   preset = de\n"
        "# in commands.conf.\n"
        "#\n"
        "# Edit this file to change the \"de\" preset.\n"
        "# Edit etc/ytnova.commands to change the default shipped layout.\n"
        "#\n"
        "# This file changes the real command layout:\n"
        "# key bindings, footer labels, actions, and optional custom commands.\n"
        "# Action IDs are internal identifiers and must not be translated.\n"
        "[DIR]\n"
        "A | A | Attribute | ACTION_CMD_A |\n"
        "K | K | Kopieren | ACTION_CMD_C |\n"
        "D | D | Datei loeschen | ACTION_CMD_D |\n"
        "F | F | Filter | ACTION_FILTER |\n"
        "G | G | Global | ACTION_CMD_G |\n"
        "I | I | Invertieren | ACTION_INVERT |\n"
        "J | J | Vergleich | ACTION_COMPARE_DIR |\n"
        "L | L | Logbuch | ACTION_LOG |\n"
        "M | M | Neuer Ordner | ACTION_CMD_M |\n"
        "N | N | Neue Datei | ACTION_CMD_MKFILE |\n"
        "P | P | Pipe | ACTION_CMD_P |\n"
        "Q | Q | Beenden | ACTION_QUIT |\n"
        "R | R | Umbenennen | ACTION_CMD_R |\n"
        "S | S | Showall | ACTION_CMD_S |\n"
        "T | T | Markieren | ACTION_TAG |\n"
        "U | U | Entmarkieren | ACTION_UNTAG |\n"
        "V | V | Verschieben | ACTION_CMD_V |\n"
        "O | O | Output | ACTION_CMD_PRINT |\n"
        "X | X | eXecute | ACTION_CMD_X |\n"
        "Z | Z | Archiv | ACTION_CMD_I |\n"
        "/ | / | Sprung | ACTION_LIST_JUMP |\n"
        "` | ` | Punktdateien | ACTION_TOGGLE_HIDDEN |\n"
        "\n"
        "[ARCHIVE_DIR]\n"
        "K | K | Kopieren | ACTION_CMD_C |\n"
        "D | D | Datei loeschen | ACTION_CMD_D |\n"
        "F | F | Filter | ACTION_FILTER |\n"
        "G | G | Global | ACTION_CMD_G |\n"
        "J | J | Vergleich | ACTION_COMPARE_DIR |\n"
        "L | L | Logbuch | ACTION_LOG |\n"
        "M | M | Neuer Ordner | ACTION_CMD_M |\n"
        "P | P | Pipe | ACTION_CMD_P |\n"
        "O | O | Output | ACTION_CMD_PRINT |\n"
        "Q | Q | Beenden | ACTION_QUIT |\n"
        "R | R | Umbenennen | ACTION_CMD_R |\n"
        "S | S | Showall | ACTION_CMD_S |\n"
        "T | T | Markieren | ACTION_TAG |\n"
        "U | U | Entmarkieren | ACTION_UNTAG |\n"
        "V | V | Verschieben | ACTION_CMD_V |\n"
        "/ | / | Sprung | ACTION_LIST_JUMP |\n"
        "` | ` | Punktdateien | ACTION_TOGGLE_HIDDEN |\n"
        "\n"
        "[FILE]\n"
        "A | A | Attribute | ACTION_CMD_A |\n"
        "K | K | Kopieren | ACTION_CMD_C |\n"
        "Ctrl+K | ^K | Markierte kopieren | ACTION_CMD_TAGGED_C |\n"
        "D | D | Datei loeschen | ACTION_CMD_D |\n"
        "E | E | Editieren | ACTION_CMD_E |\n"
        "F | F | Filter | ACTION_FILTER |\n"
        "H | H | Hex | ACTION_CMD_H |\n"
        "I | I | Invertieren | ACTION_INVERT |\n"
        "J | J | Vergleich | ACTION_COMPARE_FILE |\n"
        "L | L | Logbuch | ACTION_LOG |\n"
        "V | V | Verschieben | ACTION_CMD_M |\n"
        "Ctrl+N | ^N | Markierte verschieben | ACTION_CMD_TAGGED_M |\n"
        "N | N | Neue Datei | ACTION_CMD_MKFILE |\n"
        "P | P | Pipe | ACTION_CMD_P |\n"
        "Q | Q | Beenden | ACTION_QUIT |\n"
        "R | R | Umbenennen | ACTION_CMD_R |\n"
        "S | S | Sortieren | ACTION_CMD_S |\n"
        "O | O | Output | ACTION_CMD_PRINT |\n"
        "X | X | eXecute | ACTION_CMD_X |\n"
        "Y | Y | Pfadkopie | ACTION_CMD_Y |\n"
        "Z | Z | Archiv | ACTION_CMD_I |\n"
        "/ | / | Sprung | ACTION_LIST_JUMP |\n"
        "` | ` | Punktdateien | ACTION_TOGGLE_HIDDEN |\n"
        "\n"
        "[ARCHIVE_FILE]\n"
        "K | K | Kopieren | ACTION_CMD_C |\n"
        "D | D | Datei loeschen | ACTION_CMD_D |\n"
        "F | F | Filter | ACTION_FILTER |\n"
        "H | H | Hex | ACTION_CMD_H |\n"
        "I | I | Invertieren | ACTION_INVERT |\n"
        "J | J | Vergleich | ACTION_COMPARE_FILE |\n"
        "V | V | Verschieben | ACTION_CMD_M |\n"
        "P | P | Pipe | ACTION_CMD_P |\n"
        "O | O | Output | ACTION_CMD_PRINT |\n"
        "R | R | Umbenennen | ACTION_CMD_R |\n"
        "S | S | Sortieren | ACTION_CMD_S |\n"
        "T | T | Markieren | ACTION_TAG |\n"
        "U | U | Entmarkieren | ACTION_UNTAG |\n"
        "Y | Y | Pfadkopie | ACTION_CMD_Y |\n"
        "/ | / | Sprung | ACTION_LIST_JUMP |\n"
        "` | ` | Punktdateien | ACTION_TOGGLE_HIDDEN |\n"
    },
    {"en",
        "# Alternative YtreeNova command layout: en\n"
        "#\n"
        "# This file defines the named \"en\" command preset.\n"
        "# It is an alternative to the default layout in etc/ytnova.commands.\n"
        "#\n"
        "# YtreeNova uses this file only if the user selects:\n"
        "#   preset = en\n"
        "# in commands.conf.\n"
        "#\n"
        "# Edit this file to change the \"en\" preset.\n"
        "# Edit etc/ytnova.commands to change the default shipped layout.\n"
        "#\n"
        "# This file changes the real command layout:\n"
        "# key bindings, footer labels, actions, and optional custom commands.\n"
        "# Action IDs are internal identifiers and must not be translated.\n"
        "[DIR]\n"
        "A | A | Attributes | ACTION_CMD_A |\n"
        "C | C | Copy | ACTION_CMD_C |\n"
        "D | D | Delete | ACTION_CMD_D |\n"
        "F | F | Filter | ACTION_FILTER |\n"
        "G | G | Global | ACTION_CMD_G |\n"
        "I | I | Invert | ACTION_INVERT |\n"
        "J | J | Compare | ACTION_COMPARE_DIR |\n"
        "L | L | Log | ACTION_LOG |\n"
        "M | M | Makedir | ACTION_CMD_M |\n"
        "N | N | Newfile | ACTION_CMD_MKFILE |\n"
        "P | P | Pipe | ACTION_CMD_P |\n"
        "Q | Q | Quit | ACTION_QUIT |\n"
        "R | R | Rename | ACTION_CMD_R |\n"
        "S | S | Showall | ACTION_CMD_S |\n"
        "T | T | Tag | ACTION_TAG |\n"
        "U | U | Untag | ACTION_UNTAG |\n"
        "V | V | Movedir | ACTION_CMD_V |\n"
        "O | O | Output | ACTION_CMD_PRINT |\n"
        "X | X | Execute | ACTION_CMD_X |\n"
        "Z | Z | Archive | ACTION_CMD_I |\n"
        "/ | / | Jump | ACTION_LIST_JUMP |\n"
        "` | ` | Dotfiles | ACTION_TOGGLE_HIDDEN |\n"
        "\n"
        "[ARCHIVE_DIR]\n"
        "C | C | Copy | ACTION_CMD_C |\n"
        "D | D | Delete | ACTION_CMD_D |\n"
        "F | F | Filter | ACTION_FILTER |\n"
        "G | G | Global | ACTION_CMD_G |\n"
        "J | J | Compare | ACTION_COMPARE_DIR |\n"
        "L | L | Log | ACTION_LOG |\n"
        "M | M | Makedir | ACTION_CMD_M |\n"
        "P | P | Pipe | ACTION_CMD_P |\n"
        "O | O | Output | ACTION_CMD_PRINT |\n"
        "Q | Q | Quit | ACTION_QUIT |\n"
        "R | R | Rename | ACTION_CMD_R |\n"
        "S | S | Showall | ACTION_CMD_S |\n"
        "T | T | Tag | ACTION_TAG |\n"
        "U | U | Untag | ACTION_UNTAG |\n"
        "V | V | Movedir | ACTION_CMD_V |\n"
        "/ | / | Jump | ACTION_LIST_JUMP |\n"
        "` | ` | Dotfiles | ACTION_TOGGLE_HIDDEN |\n"
        "\n"
        "[FILE]\n"
        "A | A | Attributes | ACTION_CMD_A |\n"
        "C | C | Copy | ACTION_CMD_C |\n"
        "Ctrl+K | ^K | Copy tagged | ACTION_CMD_TAGGED_C |\n"
        "D | D | Delete | ACTION_CMD_D |\n"
        "E | E | Edit | ACTION_CMD_E |\n"
        "F | F | Filter | ACTION_FILTER |\n"
        "H | H | Hex | ACTION_CMD_H |\n"
        "I | I | Invert | ACTION_INVERT |\n"
        "J | J | Compare | ACTION_COMPARE_FILE |\n"
        "L | L | Log | ACTION_LOG |\n"
        "M | M | Move | ACTION_CMD_M |\n"
        "Ctrl+N | ^N | Move tagged | ACTION_CMD_TAGGED_M |\n"
        "N | N | Newfile | ACTION_CMD_MKFILE |\n"
        "P | P | Pipe | ACTION_CMD_P |\n"
        "Q | Q | Quit | ACTION_QUIT |\n"
        "R | R | Rename | ACTION_CMD_R |\n"
        "S | S | Sort | ACTION_CMD_S |\n"
        "O | O | Output | ACTION_CMD_PRINT |\n"
        "X | X | Execute | ACTION_CMD_X |\n"
        "Y | Y | Pathcopy | ACTION_CMD_Y |\n"
        "Z | Z | Archive | ACTION_CMD_I |\n"
        "/ | / | Jump | ACTION_LIST_JUMP |\n"
        "` | ` | Dotfiles | ACTION_TOGGLE_HIDDEN |\n"
        "\n"
        "[ARCHIVE_FILE]\n"
        "C | C | Copy | ACTION_CMD_C |\n"
        "D | D | Delete | ACTION_CMD_D |\n"
        "F | F | Filter | ACTION_FILTER |\n"
        "H | H | Hex | ACTION_CMD_H |\n"
        "I | I | Invert | ACTION_INVERT |\n"
        "J | J | Compare | ACTION_COMPARE_FILE |\n"
        "M | M | Move | ACTION_CMD_M |\n"
        "P | P | Pipe | ACTION_CMD_P |\n"
        "O | O | Output | ACTION_CMD_PRINT |\n"
        "R | R | Rename | ACTION_CMD_R |\n"
        "S | S | Sort | ACTION_CMD_S |\n"
        "T | T | Tag | ACTION_TAG |\n"
        "U | U | Untag | ACTION_UNTAG |\n"
        "Y | Y | Pathcopy | ACTION_CMD_Y |\n"
        "/ | / | Jump | ACTION_LIST_JUMP |\n"
        "` | ` | Dotfiles | ACTION_TOGGLE_HIDDEN |\n"
    },
};

static const size_t default_command_presets_catalog_count =
    sizeof(default_command_presets_catalog) /
    sizeof(default_command_presets_catalog[0]);
