static const char default_theme_catalog[] =
    "# YtreeNova semantic themes.\n"
    "#\n"
    "# Copy this file to ~/.config/ytnova/themes.conf for user-specific themes.\n"
    "# The home-directory fallback path is ~/.ytnova.themes when the XDG target\n"
    "# cannot be used.\n"
    "#\n"
    "# Role syntax:\n"
    "#   foreground\n"
    "#   +foreground\n"
    "#   foreground on background\n"
    "#   +foreground on +background\n"
    "#\n"
    "# File-type palettes are optional per theme. Rule order is significant: the\n"
    "# first matching selector wins. Omitted backgrounds inherit from the active\n"
    "# filename/window background. Terminal COLOR_PAIRS is finite, so keep the number\n"
    "# of distinct foreground/background styles small; selectors sharing a style share\n"
    "# one terminal color pair.\n"
    "\n"
    "[theme norton-blue]\n"
    "background = blue\n"
    "static_text = white\n"
    "dynamic_text = +white\n"
    "# margin = dynamic_text\n"
    "# uses fallback from dynamic_text\n"
    "dialog = white\n"
    "box_lines = white\n"
    "tree_lines = white\n"
    "keybind = yellow\n"
    "footer = white\n"
    "help = black on white\n"
    "help_footer = help\n"
    "help_heading = blue\n"
    "help_topic = blue\n"
    "help_attention = red\n"
    "help_alert = red on yellow\n"
    "help_keybind = yellow on cyan\n"
    "help_link = black on cyan\n"
    "help_link_selection = yellow on cyan\n"
    "# help_box_lines = black on white\n"
    "# uses fallback from help fg/bg\n"
    "selection = black on cyan\n"
    "picker = white on cyan\n"
    "picker_selection = white on black\n"
    "info = black on cyan\n"
    "warning = black on yellow\n"
    "error = +white on red\n"
    "search_hit = black on yellow\n"
    "\n"
    "[file-types norton-blue]\n"
    "archives = +green: 7z,Z,aab,aar,ace,apk,arc,arj,ark,bz2,cab,cpio,deb,gz,lha,lz,lz4,lzh,lzma,lzo,rar,rpm,tar,tbz,tbz2,tgz,tlz,txz,tzo,tzst,vsix,xapk,xz,zip,zoo,zst\n"
    "scripts = +cyan: sh,bash,py,pl,pm,rb,awk,bat,cmd,cgi,js,mjs,tcl,tk,ps1,lua\n"
    "code = cyan: c,h,cc,hh,cpp,cxx,hpp,asm,java,jav,jasm,go,rs,cs,ts,tsx,php,phps,pas,inc,m4,st,mak,sl,ada,caml,ml,mli,mly,mll,mlp,sas,prg,hs,hi,erl,swift,diff,patch\n"
    "audio = green: mp3,wav,flac,ogg,m4a,wma,aac,mid,midi,ac3,ape,awb,dts,it,med,mod,s3m,umx,xm,opus\n"
    "video = green: mp4,avi,mkv,mov,wmv,flv,webm,3gp,asf,m4v,mol,mpl,mp2,mpeg,mpg,ogv,ts,vob,y4m\n"
    "graphics = +magenta: jpg,jpeg,gif,png,tif,tiff,pcx,bmp,xpm,xbm,eps,pic,rle,ico,wmf,omf,ai,cdr,svg,dwg,avif,heic,heif,hif,jp2,jxl,psb,psd,xcf,webp\n"
    "documents = yellow: pdf,txt,md,markdown,doc,docx,rtf,chm,css,ctl,diz,docm,dtd,fodg,fodp,fods,fodt,htm,html,json,letter,lsm,mail,man,me,mkd,msg,nroff,odg,odp,ods,odt,po,ppt,pptm,pptx,ps,sgml,shtml,tex,text,xls,xlsm,xlsx,xml,xsd,xslt,yaml,toml\n"
    "links = yellow on blue: LINK\n"
    "executables = +green: EXEC\n"
    "\n"
    "[theme quiet-blue]\n"
    "background = blue\n"
    "box_lines = cyan\n"
    "tree_lines = +white\n"
    "static_text = white\n"
    "dynamic_text = +white\n"
    "# margin = dynamic_text\n"
    "# uses fallback from dynamic_text\n"
    "keybind = +white\n"
    "footer = white\n"
    "selection = black on white\n"
    "dialog = white\n"
    "picker = black on cyan\n"
    "# picker_selection = selection\n"
    "# uses fallback from selection\n"
    "help = white\n"
    "help_footer = help\n"
    "help_heading = help\n"
    "help_topic = help_heading\n"
    "help_attention = help_topic\n"
    "help_alert = help_attention\n"
    "# help_keybind = keybind\n"
    "# uses fallback from keybind on help_footer background\n"
    "help_link = cyan\n"
    "help_link_selection = yellow\n"
    "help_box_lines = cyan on blue\n"
    "info = black on cyan\n"
    "warning = black on yellow\n"
    "error = +white on red\n"
    "search_hit = black on yellow\n"
    "\n"
    "[file-types quiet-blue]\n"
    "archives = red: tar,tgz,zip,gz,rar,7z,iso\n"
    "scripts = +cyan: sh,bash,py,pl,rb\n"
    "code = yellow: c,h,cpp,rs,go,java,js,ts\n"
    "media = magenta: jpg,png,gif,mp4,mp3,wav\n"
    "documents = white: pdf,txt,md,doc,docx\n"
    "links = cyan: LINK\n"
    "executables = green: EXEC\n"
    "\n"
    "[theme bash-black]\n"
    "background = black\n"
    "box_lines = grey\n"
    "tree_lines = white\n"
    "static_text = white\n"
    "dynamic_text = +white\n"
    "# margin = dynamic_text\n"
    "# uses fallback from dynamic_text\n"
    "keybind = +white\n"
    "footer = white\n"
    "selection = black on white\n"
    "dialog = white\n"
    "picker = black on grey\n"
    "# picker_selection = selection\n"
    "# uses fallback from selection\n"
    "help = white\n"
    "help_footer = help\n"
    "help_heading = help\n"
    "help_topic = help_heading\n"
    "help_attention = help_topic\n"
    "help_alert = help_attention\n"
    "# help_keybind = keybind\n"
    "# uses fallback from keybind on help_footer background\n"
    "help_link = cyan\n"
    "help_link_selection = yellow\n"
    "help_box_lines = grey on black\n"
    "info = white on blue\n"
    "warning = black on yellow\n"
    "error = white on red\n"
    "search_hit = black on yellow\n"
    "\n"
    "[file-types bash-black]\n"
    "archives = red: tar,tgz,zip,gz,rar,7z,iso\n"
    "scripts = +cyan: sh,bash,py,pl,rb\n"
    "code = green: c,h,cpp,rs,go,java,js,ts\n"
    "media = magenta: jpg,png,gif,mp4,mp3,wav\n"
    "documents = white: pdf,txt,md,doc,docx\n"
    "links = cyan: LINK\n"
    "executables = green: EXEC\n"
    ;
