static const char default_theme_catalog[] =
    "# YtreeNova semantic themes.\n"
    "#\n"
    "# Copy this file to ~/.config/ytnova/themes.conf for user-specific themes.\n"
    "# The home-directory fallback path is ~/.ytnova.themes when the XDG target\n"
    "# cannot be used.\n"
    "#\n"
    "# Role syntax:\n"
    "#   foreground\n"
    "#   +foreground\n"
    "#   foreground on background\n"
    "#   +foreground on +background\n"
    "#\n"
    "# File-type palettes are optional per theme. Rule order is significant: the\n"
    "# first matching selector wins. Omitted backgrounds inherit from the active\n"
    "# filename/window background.\n"
    "\n"
    "[theme classic-blue]\n"
    "background = blue\n"
    "box_lines = cyan on blue\n"
    "tree_lines = +white on blue\n"
    "margin = dynamic_text\n"
    "static_text = white on blue\n"
    "dynamic_text = +white on blue\n"
    "keybind = +white on blue\n"
    "selection = black on +grey\n"
    "dialog = black on +grey\n"
    "picker = black on +grey\n"
    "help = white on blue\n"
    "info = +white on blue\n"
    "warning = black on yellow\n"
    "error = +white on red\n"
    "search_hit = black on yellow\n"
    "disabled = grey on blue\n"
    "\n"
    "[file-types classic-blue]\n"
    "\n"
    "[theme bash-black]\n"
    "background = black\n"
    "box_lines = grey on black\n"
    "tree_lines = white on black\n"
    "margin = dynamic_text\n"
    "static_text = white on black\n"
    "dynamic_text = +white on black\n"
    "keybind = +white on black\n"
    "selection = black on yellow\n"
    "dialog = white on black\n"
    "picker = black on yellow\n"
    "help = white on black\n"
    "info = +white on blue\n"
    "warning = black on yellow\n"
    "error = +white on red\n"
    "search_hit = black on yellow\n"
    "disabled = grey on black\n"
    "\n"
    "[file-types bash-black]\n"
    "archives = red: tar,tgz,zip,gz,rar,7z,iso\n"
    "scripts = +cyan: sh,bash,py,pl,rb\n"
    "code = green: c,h,cpp,rs,go,java,js,ts\n"
    "media = magenta: jpg,png,gif,mp4,mp3,wav\n"
    "documents = white: pdf,txt,md,doc,docx\n"
    "links = cyan: LINK\n"
    "executables = green: EXEC\n"
    ;
