/* Auto-generated from etc/ytree.conf for --init profile output. */
static const char default_profile_template[] =
"###############################################\n"
"# Ytree Defaults\n"
"# Modify this file and copy it to the hidden\n"
"# file called .ytree placed in your home directory.\n"
"# Or run: ytree --init\n"
"# You may also invoke it explicitly with the\n"
"# \"-p <profile-filename> command line argument.\n"
"###############################################\n"
"\n"
"[GLOBAL]\n"
"# AUTO_REFRESH: Add values to combine modes.\n"
"# 1 Enable File System Watcher.\n"
"# 2 Refresh on Directory Navigation selection.\n"
"# 4 Refresh when entering the File Window.\n"
"AUTO_REFRESH=3\n"
"TREEDEPTH=1\n"
"FILEMODE=2\n"
"NUMBERSEP=.\n"
"SMALLWINDOWSKIP=1\n"
"VI_KEYS=0\n"
"AUDIBLEERROR=1\n"
"CONFIRMQUIT=0\n"
"\n"
"# VI_KEYS note:\n"
"#   Runtime profile setting (0=off, 1=on).\n"
"#   When enabled, h/j/k/l and Ctrl-D/Ctrl-U are reserved for navigation.\n"
"#   Colliding commands move to uppercase (H/J/K/L, plus file-view D/U).\n"
"\n"
"# HIGHLIGHT_FULL_LINE: Set to 1 to highlight the entire line for the selected\n"
"# entry. Set to 0 for the classic behavior, which highlights only the filename.\n"
"HIGHLIGHT_FULL_LINE=0\n"
"\n"
"# HIDEDOTFILES: Set to 1 to hide files and directories starting with a dot by\n"
"# default. Set to 0 to show them. This can be toggled with the ` key.\n"
"HIDEDOTFILES=1\n"
"\n"
"# ANIMATION: Set to 1 to enable the warp-speed starfield animation\n"
"# during directory scanning. Set to 0 for the classic static logo.\n"
"ANIMATION=0\n"
"\n"
"#LISTJUMP search: 0== standard (one key); 1==incremental\n"
"LISTJUMPSEARCH=0\n"
"# SEARCHCOMMAND=grep  {}\n"
"\n"
"# Configure if the internal HEX-Viewer/Editor should display\n"
"# Adress-Offsets in hex (HEX) or decimal (DECIMAL)\n"
"HEXEDITOFFSET=HEX\n"
"\n"
"# Make Ytree start in file window mode, in a specified directory\n"
"# The \"root\" directory for Ytree is specified on the command\n"
"# line; INITIALDIR must be a directory under this root directory.\n"
"# The form may be \".\", \"/full/path/userhome/test/alpha/beta\",\n"
"# \"./alpha/beta\", \"~/test/alpha/beta\", or \"beta\"\n"
"# INITIALDIR=./alpha/beta\n"
"\n"
"# You can create a custom view by defining the variable USERVIEW\n"
"\n"
"# %tag: Tag-Symbol\n"
"# %fnm: Filename\n"
"# %atr: Attributes\n"
"# %lct: Link-Count\n"
"# %fsz: File-Size\n"
"# %mot: Modification Time\n"
"# %lnm: Symbolik Link-Name\n"
"# %uid: User-ID\n"
"# %gid: Group-ID\n"
"# %ino: Inode\n"
"# %act: Access Time\n"
"# %sct: Status Change Time\n"
"\n"
"# USERVIEW=%tag%fnm %atr %lct %fsz %mot\n"
"\n"
"# Uncomment the following lines to customize external helper programs.\n"
"# CAT=cat\n"
"EDITOR=vim\n"
"# FILEDIFF controls the file compare helper.\n"
"# Supports placeholders %1 (source) and %2 (target); if omitted, ytree appends\n"
"# source and target paths as arguments.\n"
"# FILEDIFF=diff -u\n"
"# DIRDIFF controls the external directory compare helper.\n"
"# DIRDIFF=diff -ru\n"
"# TREEDIFF controls the external tree compare helper.\n"
"# Leave empty to reuse DIRDIFF behavior by default.\n"
"# TREEDIFF=\n"
"# HEXDUMP=builtin\n"
"# MANROFF=nroff -man\n"
"# MELD=meld\n"
"# PAGER=less -cen\n"
"# TAGGEDVIEWER controls `^V` (View Tagged) mode:\n"
"#   external = use PAGER (default, less-style behavior)\n"
"#   internal = use Ytree internal tagged viewer (space/n/p handling in Ytree)\n"
"TAGGEDVIEWER=internal\n"
"\n"
"#############################\n"
"# Bracketed [] sections may appear in any order after the\n"
"# initial global configuration section.\n"
"#############################\n"
"\n"
"#\n"
"# UI Color Customization\n"
"# Colors can be specified as:\n"
"# Each color pair is written as: foreground,background\n"
"# 1. Standard colors: black(0), red(1), green(2), yellow(3), blue(4), magenta(5), cyan(6), white(7)\n"
"#    Bright colors: black(8), red(9), green(10), yellow(11), blue(12), magenta(13), cyan(14), white(15)\n"
"# 2. Numeric codes (0-255) for 256-color terminals (e.g., TERM=xterm-256color)\n"
"#\n"
"[COLORS]\n"
"# Default \"Terminal Classic\" (Bash-like 256-color Theme)\n"
"# Dull white on black, bright white hotkeys, dull yellow highlights.\n"
"# DIR_COLOR=7,0       # Dull White on Black\n"
"# HIDIR_COLOR=0,3     # Black on Dull Yellow (Selection)\n"
"# WINDIR_COLOR=7,0    # Window text/borders\n"
"# FILE_COLOR=7,0      # File list text\n"
"# HIFILE_COLOR=0,3    # Black on Dull Yellow (Selection)\n"
"# WINFILE_COLOR=7,0   # File window text/borders\n"
"# STATS_COLOR=7,0     # Directory/File stats panel text\n"
"# WINSTATS_COLOR=7,0  # Stats window text/borders\n"
"# BORDERS_COLOR=8,0   # Bright Black (Gray) borders\n"
"# MENU_COLOR=7,0      # Footer Menu Text\n"
"# HIMENUS_COLOR=15,0  # Footer Key Bindings (Bright White)\n"
"# WINERR_COLOR=15,1   # Bright White on Red\n"
"# HST_COLOR=7,0       # Text background for F2 History\n"
"# HIHST_COLOR=0,3     # Selected entry in F2 History\n"
"# WINHST_COLOR=7,0    # Window background for F2 History\n"
"# GLOBAL_COLOR=3,0    # Search-hit text (non-selected)\n"
"# HIGLOBAL_COLOR=15,3 # Search-hit highlight (selected)\n"
"# INFO_COLOR=15,4     # Bright White on Blue\n"
"# WARN_COLOR=11,0     # Bright Yellow on Black\n"
"# ERR_COLOR=15,1      # Bright White on Red\n"
"\n"
"# Example \"Classic Ytree\" color scheme\n"
"# DIR_COLOR=white,blue        # Directory text\n"
"# HIDIR_COLOR=black,white     # Selected directory entry\n"
"# WINDIR_COLOR=cyan,blue      # Directory window text/borders\n"
"# FILE_COLOR=white,blue       # File list text\n"
"# HIFILE_COLOR=black,white    # Selected file entry\n"
"# WINFILE_COLOR=cyan,blue     # File window text/borders\n"
"# STATS_COLOR=blue,cyan       # Directory/File stats panel text\n"
"# WINSTATS_COLOR=blue,cyan    # Stats window text/borders\n"
"# BORDERS_COLOR=blue,cyan     # Window borders\n"
"# MENU_COLOR=cyan,blue        # Footer menu text\n"
"# HIMENUS_COLOR=white,blue    # Footer key bindings\n"
"# WINERR_COLOR=blue,white     # Error dialog text/background\n"
"# HST_COLOR=yellow,cyan       # F2 History text\n"
"# HIHST_COLOR=white,white     # Selected F2 History entry\n"
"# WINHST_COLOR=yellow,cyan    # F2 History window text/borders\n"
"# GLOBAL_COLOR=yellow,cyan    # Search-hit text (non-selected)\n"
"# HIGLOBAL_COLOR=white,yellow # Search-hit highlight (selected)\n"
"# INFO_COLOR=white,blue       # Info dialog text/background\n"
"# WARN_COLOR=yellow,black     # Warning text/background\n"
"# ERR_COLOR=red,white         # Error text/background\n"
"\n"
"#\n"
"# File Type Colorization\n"
"# Rules are checked in order. Special keywords are DIR, LINK, EXEC.\n"
"# Wildcards are supported for filename patterns.\n"
"#\n"
"[FILE_COLORS]\n"
"# Standard Bash/LS colors on Black background\n"
"DIR=4,0       # Blue\n"
"LINK=6,0      # Cyan\n"
"EXEC=2,0      # Green\n"
"\n"
"# --- Archives (Red) ---\n"
"*.tar=1,0\n"
"*.tgz=1,0\n"
"*.arj=1,0\n"
"*.taz=1,0\n"
"*.lzh=1,0\n"
"*.zip=1,0\n"
"*.z=1,0\n"
"*.Z=1,0\n"
"*.gz=1,0\n"
"*.bz2=1,0\n"
"*.deb=1,0\n"
"*.rpm=1,0\n"
"*.jar=1,0\n"
"*.rar=1,0\n"
"*.7z=1,0\n"
"*.iso=1,0\n"
"*.img=1,0\n"
"\n"
"# --- Images (Magenta - Color 5) ---\n"
"*.jpg=5,0\n"
"*.jpeg=5,0\n"
"*.gif=5,0\n"
"*.bmp=5,0\n"
"*.png=5,0\n"
"*.tif=5,0\n"
"*.tiff=5,0\n"
"*.svg=5,0\n"
"*.webp=5,0\n"
"*.ico=5,0\n"
"\n"
"# --- Video (Magenta - Color 5) ---\n"
"*.avi=5,0\n"
"*.mpg=5,0\n"
"*.mpeg=5,0\n"
"*.mp4=5,0\n"
"*.mkv=5,0\n"
"*.mov=5,0\n"
"*.wmv=5,0\n"
"*.flv=5,0\n"
"*.webm=5,0\n"
"\n"
"# --- Audio (Cyan - Color 6) ---\n"
"*.mp3=6,0\n"
"*.wav=6,0\n"
"*.flac=6,0\n"
"*.ogg=6,0\n"
"*.m4a=6,0\n"
"*.aac=6,0\n"
"*.wma=6,0\n"
"*.mid=6,0\n"
"\n"
"# --- Documents (White/Default or maybe Yellow for emphasis?) ---\n"
"*.pdf=7,0\n"
"*.epub=7,0\n"
"*.mobi=7,0\n"
"*.doc=7,0\n"
"*.docx=7,0\n"
"*.xls=7,0\n"
"*.xlsx=7,0\n"
"*.ppt=7,0\n"
"*.pptx=7,0\n"
"*.odt=7,0\n"
"*.ods=7,0\n"
"*.odp=7,0\n"
"*.odg=7,0\n"
"*.odf=7,0\n"
"*.odb=7,0\n"
"*.txt=7,0\n"
"*.rtf=7,0\n"
"*.md=7,0\n"
"\n"
"[VIEWER]\n"
".jpg,.gif,.bmp,.tif,.ppm,.xpm=xv -\n"
".1,.2,.3,.4,.5,.6,.7,.8,.n=nroff -man - | less\n"
".ps=ghostview\n"
".mid=timidity -id\n"
".wav=splay\n"
".au=auplay\n"
".avi,.mpg,.mov=xanim\n"
".htm,.html=lynx\n"
".pdf,.PDF=okular\n"
".mp3=mpg123\n"
"\n"
"######################################\n"
"# The values DIR1, DIR2, FILE1, and FILE2 in the [MENU] section redefine the text\n"
"# presented in menu lines 1 and 2 of the DIR and FILE windows, respectively.  The\n"
"# mapping of the keyboard is not changed here, just the text presented to the user.\n"
"######################################\n"
"\n"
"[MENU]\n"
"# DIR1=DIR-CUST  (A)ttribute (B)->a (D)elete  (F)ilespec (G)roup (k)-du (K)-dirpath (L)og (Q)uit\n"
"# DIR2=COMMANDS  (M)akedir (O)wner (P)ath/owner (R)ename (S)howall (T)ag (U)ntag e(X)ecute   (^F) dirmode\n"
"# FILE1=FILE-CUST (A)ttribute (C)opy (D)elete (E)dit (F)ilespec (G)cc (H)ex (I)->v (L)ogin (M)ove  (Q)uit\n"
"# FILE2=COMMANDS  (O)wner (P)ipe (R)ename (S)ort (T)ag (U)ntag (V)iew (W)c e(X)ecute pathcop(Y) (^F)ilemode\n"
"\n"
"######################################\n"
"# The [DIRMAP] and [FILEMAP] sections allow keyboard keys to be remapped or unmapped\n"
"# in directory mode and file mode, respectively.  The comma-separated list of keys to\n"
"# the left of the \"=\" is remapped to perform the action specified by the character to\n"
"# the right of the \"=\".  If no character is specified, the keys are unmapped (do nothing).\n"
"######################################\n"
"[DIRMAP]\n"
"# <B> or <b> in dir window mode is remapped to <a> key action (Attribute)\n"
"# B,b=a\n"
"# <P> or <p> in dir window mode is remapped to <o> key action (Owner)\n"
"# P,p=o\n"
"\n"
"[FILEMAP]\n"
"# <I> in file window mode is remapped to <v> key action (View)\n"
"# i,I=v\n"
"# <G> in file window mode is remapped to <g>\n"
"# G=g\n"
"# Ytree default assignment of <g> to \"group\" is removed\n"
"# g=\n"
"\n"
"######################################\n"
"# The [DIRCMD] and [FILECMD] sections allow new command actions to be defined\n"
"# in directory mode and file mode, respectively.  The command to the right of\n"
"# the \"=\" is executed when the key to the right of the \"=\" is pressed.  If the\n"
"# key is mapped (either by the default Ytree key assignments or by a [DIRMAP]\n"
"# or [FILEMAP] entry,) this mapping is followed after the command is executed.\n"
"# Thus to change FILE mode \"g\" from \"group\" to \"gcc\" requires both a FILECMD\n"
"# assignment \"g=gcc -O -c\" and a FILEMAP assignment \"g=\" (to remove the default\n"
"# action \"group\" from the \"g\" key.)\n"
"#\n"
"# If [command] contains the characters \"%s\", the selected <filepath> is\n"
"# substituted for \"%s\".  Otherwise, the selected <filepath> is appended to [command].\n"
"######################################\n"
"[DIRCMD]\n"
"# <k> in dir window mode does \"du <dirname> | less\"\n"
"# k=du %s | less\n"
"# <K> in dir window mode does \"echo <dirname> | less\"\n"
"# K=echo %s | less\n"
"# <p> in dir window mode does \"echo <dirname> | less\"\n"
"# p=echo %s | less\n"
"\n"
"[FILECMD]\n"
"# <g>  in file window mode does \"gcc -O -c <filename>\"\n"
"# g=gcc -O -c\n"
"# <w>  in file window mode does \"wc <filename> | less\"\n"
"# w=wc %s | less\n"
;
