/* Auto-generated from etc/ytnova.commands for commands.conf starter output. */
static const char default_commands_catalog[] =
    "######################################\n"
    "# commands.conf starter for YtreeNova command customization.\n"
    "#\n"
    "# This is the package's default command set.\n"
    "# YtreeNova uses it when commands.conf does not select a preset.\n"
    "# If you want to change what ships by default, edit this file.\n"
    "# If you want to change what \"preset = en\" means, edit etc/commands/en.conf\n"
    "# instead.\n"
    "#\n"
    "# Only --init and explicit F10 Commands create this file. When the file is\n"
    "# missing, YtreeNova falls back to the packaged active command map without\n"
    "# creating a user copy.\n"
    "#\n"
    "# Optional preset selector:\n"
    "#   preset = de\n"
    "#\n"
    "# Canonical structure:\n"
    "#   [DIR]\n"
    "#   binding | shown | label | action | command\n"
    "#\n"
    "#   [ARCHIVE_DIR]\n"
    "#   binding | shown | label | action | command\n"
    "#\n"
    "#   [FILE]\n"
    "#   binding | shown | label | action | command\n"
    "#\n"
    "#   [ARCHIVE_FILE]\n"
    "#   binding | shown | label | action | command\n"
    "#\n"
    "# Rules:\n"
    "# - section headers are stable runtime command-surface IDs, not locale names.\n"
    "# - preset selects one packaged read-only preset by stable ID before local rows.\n"
    "# - binding is the real input key (single keys or Ctrl+letter chords).\n"
    "# - shown is the token rendered in footer keybinding/F1 surfaces.\n"
    "# - label is plain user-visible text only; do not encode key markup here.\n"
    "# - action is the stable internal action ID; do not translate or rename it.\n"
    "# - command is blank for built-ins. Use action user-command for custom shell\n"
    "#   commands and put the shell command in the final column.\n"
    "# - Uppercase and lowercase letters may be bound separately.\n"
    "# - Ctrl+letter bindings are case-insensitive, so Ctrl+n and Ctrl+N are the\n"
    "#   same chord.\n"
    "#\n"
    "# Built-in rows below mirror the packaged default visible command keys. Editing\n"
    "# them lets commands.conf override the packaged active command map cleanly.\n"
    "######################################\n"
    "[DIR]\n"
    "# binding | shown | label | action | command\n"
    "A | A | Attributes | ACTION_CMD_A |\n"
    "C | C | Copy | ACTION_CMD_C |\n"
    "D | D | Delete | ACTION_CMD_D |\n"
    "F | F | Filter | ACTION_FILTER |\n"
    "G | G | Global | ACTION_CMD_G |\n"
    "I | I | Invert | ACTION_INVERT |\n"
    "J | J | Compare | ACTION_COMPARE_DIR |\n"
    "L | L | Log | ACTION_LOG |\n"
    "M | M | Makedir | ACTION_CMD_M |\n"
    "N | N | Newfile | ACTION_CMD_MKFILE |\n"
    "O | O | Only tagged | ACTION_TOGGLE_TAGGED_MODE |\n"
    "P | P | Pipe | ACTION_CMD_P |\n"
    "Q | Q | Quit | ACTION_QUIT |\n"
    "R | R | Rename | ACTION_CMD_R |\n"
    "S | S | Showall | ACTION_CMD_S |\n"
    "T | T | Tag | ACTION_TAG |\n"
    "U | U | Untag | ACTION_UNTAG |\n"
    "V | V | Movedir | ACTION_CMD_V |\n"
    "W | W | Write | ACTION_CMD_PRINT |\n"
    "X | X | Execute | ACTION_CMD_X |\n"
    "Z | Z | Archive | ACTION_CMD_I |\n"
    "/ | / | Jump | ACTION_LIST_JUMP |\n"
    "` | ` | Dotfiles | ACTION_TOGGLE_HIDDEN |\n"
    "\n"
    "[ARCHIVE_DIR]\n"
    "# binding | shown | label | action | command\n"
    "C | C | Copy | ACTION_CMD_C |\n"
    "D | D | Delete | ACTION_CMD_D |\n"
    "F | F | Filter | ACTION_FILTER |\n"
    "G | G | Global | ACTION_CMD_G |\n"
    "J | J | Compare | ACTION_COMPARE_DIR |\n"
    "L | L | Log | ACTION_LOG |\n"
    "M | M | Makedir | ACTION_CMD_M |\n"
    "P | P | Pipe | ACTION_CMD_P |\n"
    "Q | Q | Quit | ACTION_QUIT |\n"
    "R | R | Rename | ACTION_CMD_R |\n"
    "S | S | Showall | ACTION_CMD_S |\n"
    "T | T | Tag | ACTION_TAG |\n"
    "U | U | Untag | ACTION_UNTAG |\n"
    "V | V | Movedir | ACTION_CMD_V |\n"
    "/ | / | Jump | ACTION_LIST_JUMP |\n"
    "` | ` | Dotfiles | ACTION_TOGGLE_HIDDEN |\n"
    "\n"
    "[FILE]\n"
    "# binding | shown | label | action | command\n"
    "A | A | Attributes | ACTION_CMD_A |\n"
    "C | C | Copy | ACTION_CMD_C |\n"
    "Ctrl+K | ^K | Copy tagged | ACTION_CMD_TAGGED_C |\n"
    "D | D | Delete | ACTION_CMD_D |\n"
    "E | E | Edit | ACTION_CMD_E |\n"
    "F | F | Filter | ACTION_FILTER |\n"
    "H | H | Hex | ACTION_CMD_H |\n"
    "I | I | Invert | ACTION_INVERT |\n"
    "J | J | Compare | ACTION_COMPARE_FILE |\n"
    "L | L | Log | ACTION_LOG |\n"
    "M | M | Move | ACTION_CMD_M |\n"
    "Ctrl+N | ^N | Move tagged | ACTION_CMD_TAGGED_M |\n"
    "N | N | Newfile | ACTION_CMD_MKFILE |\n"
    "O | O | Only tagged | ACTION_TOGGLE_TAGGED_MODE |\n"
    "P | P | Pipe | ACTION_CMD_P |\n"
    "Q | Q | Quit | ACTION_QUIT |\n"
    "R | R | Rename | ACTION_CMD_R |\n"
    "S | S | Sort | ACTION_CMD_S |\n"
    "W | W | Write | ACTION_CMD_PRINT |\n"
    "X | X | Execute | ACTION_CMD_X |\n"
    "Y | Y | Pathcopy | ACTION_CMD_Y |\n"
    "Z | Z | Archive | ACTION_CMD_I |\n"
    "/ | / | Jump | ACTION_LIST_JUMP |\n"
    "` | ` | Dotfiles | ACTION_TOGGLE_HIDDEN |\n"
    "\n"
    "[ARCHIVE_FILE]\n"
    "# binding | shown | label | action | command\n"
    "C | C | Copy | ACTION_CMD_C |\n"
    "D | D | Delete | ACTION_CMD_D |\n"
    "F | F | Filter | ACTION_FILTER |\n"
    "H | H | Hex | ACTION_CMD_H |\n"
    "I | I | Invert | ACTION_INVERT |\n"
    "J | J | Compare | ACTION_COMPARE_FILE |\n"
    "M | M | Move | ACTION_CMD_M |\n"
    "P | P | Pipe | ACTION_CMD_P |\n"
    "R | R | Rename | ACTION_CMD_R |\n"
    "S | S | Sort | ACTION_CMD_S |\n"
    "T | T | Tag | ACTION_TAG |\n"
    "U | U | Untag | ACTION_UNTAG |\n"
    "Y | Y | Pathcopy | ACTION_CMD_Y |\n"
    "/ | / | Jump | ACTION_LIST_JUMP |\n"
    "` | ` | Dotfiles | ACTION_TOGGLE_HIDDEN |\n"
    "\n"
    "# Example custom shell-command row:\n"
    "# [FILE]\n"
    "# K | K | Disk usage | user-command | du %s | less\n"
    ;
