/* Auto-generated from etc/ytnova.conf for --init profile output. */
static const char default_profile_template[] =
    "###############################################\n"
    "# YtreeNova Defaults\n"
    "# Modify this file and copy it to the hidden\n"
    "# file called .ytnova placed in your home directory.\n"
    "# Or run: ytnova --init\n"
    "# You may also invoke it explicitly with the\n"
    "# \"-p <profile-filename> command line argument.\n"
    "###############################################\n"
    "\n"
    "[GLOBAL]\n"
    "# AUTO_REFRESH: Add values to combine modes.\n"
    "# 1 Enable File System Watcher.\n"
    "# 2 Refresh on Directory Navigation selection.\n"
    "# 4 Refresh when entering the File Window.\n"
    "AUTO_REFRESH=3\n"
    "TREEDEPTH=2\n"
    "FILEMODE=2\n"
    "SMALLWINDOWSKIP=1\n"
    "VI_KEYS=0\n"
    "AUDIBLEERROR=1\n"
    "# CONFIRMQUIT=0 # probably redundant\n"
    "\n"
    "# VI_KEYS note:\n"
    "#   Runtime profile setting (0=off, 1=on).\n"
    "#   When enabled, h/j/k/l and Ctrl-D/Ctrl-U are reserved for navigation.\n"
    "#   Colliding commands move to uppercase (H/J/K/L, plus file-view D/U).\n"
    "\n"
    "# HIGHLIGHT_FULL_LINE: Set to 1 to highlight the entire line for the selected\n"
    "# entry. Set to 0 for the classic behavior, which highlights only the filename.\n"
    "HIGHLIGHT_FULL_LINE=0\n"
    "\n"
    "# HIDEDOTFILES: Set to 1 to hide files and directories starting with a dot by\n"
    "# default. Set to 0 to show them. This can be toggled with the ` key.\n"
    "HIDEDOTFILES=1\n"
    "\n"
    "# ANIMATION: Set to 1 to enable the warp-speed starfield animation\n"
    "# during directory scanning. Set to 0 for the classic static logo.\n"
    "ANIMATION=0\n"
    "\n"
    "#LISTJUMP search: 0== standard (one key); 1==incremental\n"
    "# LISTJUMPSEARCH=0 # redundant\n"
    "# SEARCHCOMMAND=grep  {} # redundant\n"
    "\n"
    "# Configure if the internal HEX-Viewer/Editor should display\n"
    "# Adress-Offsets in hex (HEX) or decimal (DECIMAL)\n"
    "HEXEDITOFFSET=HEX\n"
    "\n"
    "# Make YtreeNova start in file window mode, in a specified directory\n"
    "# The \"root\" directory for YtreeNova is specified on the command\n"
    "# line; INITIALDIR must be a directory under this root directory.\n"
    "# The form may be \".\", \"/full/path/userhome/test/alpha/beta\",\n"
    "# \"./alpha/beta\", \"~/test/alpha/beta\", or \"beta\"\n"
    "# INITIALDIR=./alpha/beta\n"
    "\n"
    "# You can create a custom view by defining the variable USERVIEW\n"
    "\n"
    "# %tag: Tag-Symbol\n"
    "# %fnm: Filename\n"
    "# %atr: Attributes\n"
    "# %lct: Link-Count\n"
    "# %fsz: File-Size\n"
    "# %mot: Modification Time\n"
    "# %lnm: Symbolik Link-Name\n"
    "# %uid: User-ID\n"
    "# %gid: Group-ID\n"
    "# %ino: Inode\n"
    "# %act: Access Time\n"
    "# %sct: Status Change Time\n"
    "\n"
    "# USERVIEW=%tag%fnm %atr %lct %fsz %mot\n"
    "\n"
    "# Uncomment the following lines to customize external helper programs.\n"
    "# CAT=cat # redundant\n"
    "EDITOR=vim\n"
    "# FILEDIFF controls the file compare helper.\n"
    "# Supports placeholders %1 (source) and %2 (target); if omitted, ytnova appends\n"
    "# source and target paths as arguments.\n"
    "# FILEDIFF=diff -u\n"
    "# DIRDIFF controls the external directory compare helper.\n"
    "# DIRDIFF=diff -ru\n"
    "# TREEDIFF controls the external tree compare helper.\n"
    "# Leave empty to reuse DIRDIFF behavior by default.\n"
    "# TREEDIFF=\n"
    "# HEXDUMP=builtin # redundant\n"
    "# MANROFF=nroff -man # redundant\n"
    "# MELD=meld # redundant\n"
    "# PAGER=less -cen\n"
    "# TAGGEDVIEWER controls `^V` (View Tagged) mode:\n"
    "#   external = use PAGER (default, less-style behavior)\n"
    "#   internal = use YtreeNova internal tagged viewer (space/n/p handling in YtreeNova)\n"
    "TAGGEDVIEWER=internal\n"
    "\n"
    "# THEME selects a semantic theme from ~/.config/ytnova/themes.conf, then\n"
    "# ~/.ytnova.themes, then the packaged etc/ytnova.themes catalog.\n"
    "THEME=classic-blue\n"
    "\n"
    "#############################\n"
    "# Bracketed [] sections may appear in any order after the\n"
    "# initial global configuration section.\n"
    "#############################\n"
    "\n"
    "#\n"
    "# Theme customization lives in a separate theme catalog, not in this main\n"
    "# config profile. Copy etc/ytnova.themes to ~/.config/ytnova/themes.conf\n"
    "# and edit semantic roles such as dynamic_text, static_text, keybind,\n"
    "# selection, dialog, picker, help, warning, error, and search_hit there.\n"
    "# File-type palette rules are also theme-local so each theme controls its\n"
    "# own optional filename decoration without assuming another background.\n"
    "#\n"
    "[VIEWER]\n"
    ".jpg,.gif,.bmp,.tif,.ppm,.xpm=xv -\n"
    ".1,.2,.3,.4,.5,.6,.7,.8,.n=nroff -man - | less\n"
    ".ps=ghostview\n"
    ".mid=timidity -id\n"
    ".wav=splay\n"
    ".au=auplay\n"
    ".avi,.mpg,.mov=xanim\n"
    ".htm,.html=lynx\n"
    ".pdf,.PDF=okular\n"
    ".mp3=mpg123\n"
    "\n"
    "######################################\n"
    "# The values DIR1, DIR2, FILE1, and FILE2 in the [MENU] section redefine the text\n"
    "# presented in menu lines 1 and 2 of the DIR and FILE windows, respectively.  The\n"
    "# mapping of the keyboard is not changed here, just the text presented to the user.\n"
    "######################################\n"
    "\n"
    "[MENU]\n"
    "# DIR1=DIR-CUST  (A)ttribute (B)->a (D)elete  (F)ilespec (G)roup (k)-du (K)-dirpath (L)og (Q)uit\n"
    "# DIR2=COMMANDS  (M)akedir (O)wner (P)ath/owner (R)ename (S)howall (T)ag (U)ntag e(X)ecute   (^F) dirmode\n"
    "# FILE1=FILE-CUST (A)ttribute (C)opy (D)elete (E)dit (F)ilespec (G)cc (H)ex (I)nvert (L)og (M)ove (Q)uit\n"
    "# FILE2=COMMANDS  (O)wner (P)ipe (R)ename (S)ort (T)ag (U)ntag (V)iew (W)c e(X)ecute pathcop(Y) (^F)ilemode\n"
    "\n"
    "######################################\n"
    "# The [DIRMAP] and [FILEMAP] sections allow keyboard keys to be remapped or unmapped\n"
    "# in directory mode and file mode, respectively.  The comma-separated list of keys to\n"
    "# the left of the \"=\" is remapped to perform the action specified by the character to\n"
    "# the right of the \"=\".  If no character is specified, the keys are unmapped (do nothing).\n"
    "######################################\n"
    "[DIRMAP]\n"
    "# <B> or <b> in dir window mode is remapped to <a> key action (Attribute)\n"
    "# B,b=a\n"
    "# <P> or <p> in dir window mode is remapped to <o> key action (Owner)\n"
    "# P,p=o\n"
    "\n"
    "[FILEMAP]\n"
    "# <I> in file window mode is remapped to <v> key action (View)\n"
    "# i,I=v\n"
    "# <G> in file window mode is remapped to <g>\n"
    "# G=g\n"
    "# YtreeNova default assignment of <g> to \"group\" is removed\n"
    "# g=\n"
    "\n"
    "######################################\n"
    "# The [DIRCMD] and [FILECMD] sections allow new command actions to be defined\n"
    "# in directory mode and file mode, respectively.  The command to the right of\n"
    "# the \"=\" is executed when the key to the right of the \"=\" is pressed.  If the\n"
    "# key is mapped (either by the default YtreeNova key assignments or by a [DIRMAP]\n"
    "# or [FILEMAP] entry,) this mapping is followed after the command is executed.\n"
    "# Thus to change FILE mode \"g\" from \"group\" to \"gcc\" requires both a FILECMD\n"
    "# assignment \"g=gcc -O -c\" and a FILEMAP assignment \"g=\" (to remove the default\n"
    "# action \"group\" from the \"g\" key.)\n"
    "#\n"
    "# If [command] contains the characters \"%s\", the selected <filepath> is\n"
    "# substituted for \"%s\".  Otherwise, the selected <filepath> is appended to [command].\n"
    "######################################\n"
    "[DIRCMD]\n"
    "# <k> in dir window mode does \"du <dirname> | less\"\n"
    "# k=du %s | less\n"
    "# <K> in dir window mode does \"echo <dirname> | less\"\n"
    "# K=echo %s | less\n"
    "# <p> in dir window mode does \"echo <dirname> | less\"\n"
    "# p=echo %s | less\n"
    "\n"
    "[FILECMD]\n"
    "# <g>  in file window mode does \"gcc -O -c <filename>\"\n"
    "# g=gcc -O -c\n"
    "# <w>  in file window mode does \"wc <filename> | less\"\n"
    "# w=wc %s | less\n";
