/* Auto-generated from etc/ytnova.applications for applications.conf starter output. */
static const char default_applications_catalog[] =
    "######################################\n"
    "# applications.conf starter for YtreeNova F9 application presets.\n"
    "#\n"
    "# This is the package's default Applications menu catalog.\n"
    "# Only explicit F9 Applications edit creates a user copy. When the file is\n"
    "# missing, YtreeNova falls back to the packaged applications catalog without\n"
    "# creating a user file.\n"
    "#\n"
    "# Row format:\n"
    "#   label | prompt | command\n"
    "#\n"
    "# Rules:\n"
    "# - label is the menu text shown in F9.\n"
    "# - prompt is optional. Leave it blank to run the command immediately.\n"
    "# - command is any shell command template.\n"
    "# - `{}` means the file or folder currently selected in ytnova.\n"
    "# - `{input}` means the text you type when the preset asks for extra input.\n"
    "# - F9 launches presets and returns to ytnova immediately.\n"
    "# - If a preset needs its own terminal, wrap it in your terminal emulator or a script.\n"
    "# - ytnova does not restrict user commands, even when they duplicate built-ins.\n"
    "# Useful patterns:\n"
    "# - open selected item |  | xdg-open {}\n"
    "# - open typed URL | URL | xdg-open {input}\n"
    "# - open selected media in mpv |  | mpv {}\n"
    "# - run a local helper script |  | ~/.local/bin/my-ytnova-handler {}\n"
    "######################################\n"
    "# label | prompt | command\n"
    "wget fetch preset | URL | wget --continue --show-progress --content-disposition {input}\n"
    "ssh connect preset | Host | ssh {input}\n"
    "format convert preset | Output path | ffmpeg -nostdin -hide_banner -i {} {input}\n"
    "# open selected item |  | xdg-open {}\n"
    "# open typed URL | URL | xdg-open {input}\n"
    "# open selected media in mpv |  | mpv {}\n"
    ;
