/* Auto-generated from etc/ytnova.conf for --init profile output. */
static const char default_profile_template[] =
    "###############################################\n"
    "# YtreeNova Defaults\n"
    "# Built-in default profile template for ~/.config/ytnova/ytnova.conf.\n"
    "# If the XDG config path cannot be used, ytnova falls back to ~/.ytnova.\n"
    "# F10 Config and `ytnova --init` can write it for you.\n"
    "# You may also invoke it explicitly with the\n"
    "# \"-p <profile-filename> command line argument.\n"
    "###############################################\n"
    "\n"
    "[GLOBAL]\n"
    "# AUTO_REFRESH: Add values to combine modes.\n"
    "# 1 Enable File System Watcher.\n"
    "# 2 Refresh on Directory Navigation selection.\n"
    "# 4 Refresh when entering the File Window.\n"
    "AUTO_REFRESH=3\n"
    "TREEDEPTH=2\n"
    "# Startup always begins in the plain Name view.\n"
    "# Use the 1..9 view keys at runtime to change the active panel.\n"
    "#   1 = Name        2 = Attributes  3 = Owner  4 = Times\n"
    "#   5 = Compact Name (from 1 only)\n"
    "#   6 = Size units  7 = Mini preview\n"
    "#   8 = File        9 = Git\n"
    "# SEPARATE_DIR_FILE_VIEWS controls whether tree and file keep different 1..4 views.\n"
    "#   0 = shared (default, easier: change one and both follow)\n"
    "#   1 = separate (advanced: tree and file remember different 1..4 views)\n"
    "SEPARATE_DIR_FILE_VIEWS=0\n"
    "# FILE_SIZE_UNITS picks how sizes look in directory/file rows.\n"
    "#   human-readable = friendly sizes like 1.2K or 3.4M\n"
    "#   binary = exact byte counts with separators\n"
    "# Key 6 flips between these two size styles while ytnova is running.\n"
    "# The stats box always stays human-readable.\n"
    "FILE_SIZE_UNITS=human-readable\n"
    "SMALLWINDOWSKIP=1\n"
    "VI_KEYS=0\n"
    "AUDIBLEERROR=1\n"
    "# CONFIRMQUIT=0 # probably redundant\n"
    "\n"
    "# VI_KEYS note:\n"
    "#   Runtime profile setting (0=off, 1=on).\n"
    "#   When enabled, h/j/k/l and Ctrl-D/Ctrl-U are reserved for navigation.\n"
    "#   Colliding commands move to uppercase (H/J/K/L, plus file-view D/U).\n"
    "\n"
    "# HIGHLIGHT_FULL_LINE: Set to 1 to highlight the entire line for the selected\n"
    "# entry. Set to 0 for the classic behavior, which highlights only the filename.\n"
    "HIGHLIGHT_FULL_LINE=0\n"
    "\n"
    "# HIDEDOTFILES: Set to 1 to hide files and directories starting with a dot by\n"
    "# default. Set to 0 to show them. This can be toggled with the ` key.\n"
    "HIDEDOTFILES=1\n"
    "\n"
    "# ANIMATION: Set to 1 to enable the warp-speed starfield animation\n"
    "# during directory scanning. Set to 0 for the classic static logo.\n"
    "ANIMATION=0\n"
    "\n"
    "# LISTJUMP search: 0== standard (one key); 1==incremental\n"
    "# LISTJUMPSEARCH=0 # redundant\n"
    "# SEARCHCOMMAND=grep  {} # redundant\n"
    "\n"
    "# Configure if the internal HEX-Viewer/Editor should display\n"
    "# Adress-Offsets in hex (HEX) or decimal (DECIMAL)\n"
    "HEXEDITOFFSET=HEX\n"
    "\n"
    "# Make YtreeNova start in file window mode, in a specified directory\n"
    "# The \"root\" directory for YtreeNova is specified on the command\n"
    "# line; INITIALDIR must be a directory under this root directory.\n"
    "# The form may be \".\", \"/full/path/userhome/test/alpha/beta\",\n"
    "# \"./alpha/beta\", \"~/test/alpha/beta\", or \"beta\"\n"
    "# INITIALDIR=./alpha/beta\n"
    "\n"
    "# You can create a custom view by defining the variable USERVIEW\n"
    "\n"
    "# %tag: Tag-Symbol\n"
    "# %fnm: Filename\n"
    "# %atr: Attributes\n"
    "# %lct: Link-Count\n"
    "# %fsz: File-Size\n"
    "# %mot: Modification Time\n"
    "# %lnm: Symbolik Link-Name\n"
    "# %uid: User-ID\n"
    "# %gid: Group-ID\n"
    "# %ino: Inode\n"
    "# %act: Access Time\n"
    "# %sct: Status Change Time\n"
    "\n"
    "# USERVIEW=%tag%fnm %atr %lct %fsz %mot\n"
    "\n"
    "# Uncomment the following lines to customize external helper programs.\n"
    "# CAT=cat # redundant\n"
    "EDITOR=vim\n"
    "# FILEDIFF controls the file compare helper.\n"
    "# Supports placeholders %1 (source) and %2 (target); if omitted, ytnova appends\n"
    "# source and target paths as arguments.\n"
    "# FILEDIFF=diff -u\n"
    "# DIRDIFF controls the external directory compare helper.\n"
    "# DIRDIFF=diff -ru\n"
    "# TREEDIFF controls the external tree compare helper.\n"
    "# Leave empty to reuse DIRDIFF behavior by default.\n"
    "# TREEDIFF=\n"
    "# HEXDUMP=builtin # redundant\n"
    "# MANROFF=nroff -man # redundant\n"
    "# MELD=meld # redundant\n"
    "# PAGER=less -cen\n"
    "# TAGGEDVIEWER controls `^V` (View Tagged) mode:\n"
    "#   external = use PAGER (default, less-style behavior)\n"
    "#   internal = use YtreeNova internal tagged viewer (space/n/p handling in YtreeNova)\n"
    "TAGGEDVIEWER=internal\n"
    "\n"
    "# THEME checks ~/.config/ytnova/themes.conf first, then the home fallback\n"
    "# ~/.ytnova.themes only when the XDG target path is unavailable.\n"
    "# Missing user theme catalogs are satisfied from packaged/compiled defaults without\n"
    "# creating a user file, only --init / explicit F10 edit flows create starter files.\n"
    "# Edit semantic roles and file-type palette rules there.\n"
    "# Built-in starter themes (leave one uncommented):\n"
    "THEME=quiet-blue\n"
    "# THEME=orthodox-blue\n"
    "# THEME=bash-black\n"
    "\n"
    "[VIEWER]\n"
    ".jpg,.gif,.bmp,.tif,.ppm,.xpm=xv -\n"
    ".1,.2,.3,.4,.5,.6,.7,.8,.n=nroff -man - | less\n"
    ".ps=ghostview\n"
    ".mid=timidity -id\n"
    ".wav=splay\n"
    ".au=auplay\n"
    ".avi,.mpg,.mov=xanim\n"
    ".htm,.html=lynx\n"
    ".pdf,.PDF=okular\n"
    ".mp3=mpg123\n"
    ;
