/* Auto-generated from etc/ytnova.applications for applications.conf starter output. */
static const char default_applications_catalog[] =
    "######################################\n"
    "# applications.conf starter for YtreeNova F9 application presets.\n"
    "#\n"
    "# This is the package's default Applications menu catalog.\n"
    "# Only explicit F9 Applications edit creates a user copy. When the file is\n"
    "# missing, YtreeNova falls back to the packaged applications catalog without\n"
    "# creating a user file.\n"
    "#\n"
    "# Row format:\n"
    "#   label | prompt | command\n"
    "#\n"
    "# Rules:\n"
    "# - label is the menu text shown in F9.\n"
    "# - prompt is optional. Leave it blank to run the command immediately.\n"
    "# - command is any shell command template.\n"
    "# - `{}` means the file or folder currently selected in ytnova.\n"
    "# - `{input}` means the text you type when the preset asks for extra input.\n"
    "# - F9 launches presets and returns to ytnova immediately.\n"
    "# - If a preset needs its own terminal, wrap it in your terminal emulator or a script.\n"
    "# - ytnova does not restrict user commands, even when they duplicate built-ins.\n"
    "# Useful patterns:\n"
    "# - open selected item |  | xdg-open {}\n"
    "# - open typed URL | URL | xdg-open {input}\n"
    "# - open selected media in mpv |  | mpv {}\n"
    "# - run a local helper script |  | ~/.local/bin/my-ytnova-handler {}\n"
    "######################################\n"
    "# label | prompt | command\n"
    "\n"
    "# Download a URL, resuming a partial download and keeping the server filename.\n"
    "wget fetch preset | URL | wget --continue --show-progress --content-disposition {input}\n"
    "\n"
    "# Open an SSH session to a host entered at launch time.\n"
    "ssh connect preset | Host | ssh {input}\n"
    "\n"
    "# Convert the selected media file to the output path entered at launch time.\n"
    "format convert preset | Output path | ffmpeg -nostdin -hide_banner -i {} {input}\n"
    "\n"
    "# Requires a graphical desktop session. In a terminal-only environment, leave commented out.\n"
    "# open selected item |  | xdg-open {}\n"
    "\n"
    "# Requires a graphical desktop session. In a terminal-only environment, leave commented out.\n"
    "# open typed URL | URL | xdg-open {input}\n"
    "\n"
    "# Open selected media in mpv. Video playback normally needs a graphical display.\n"
    "# open selected media in mpv |  | mpv {}\n"
    "\n"
    "# Write same-content files in the selected directory to a report in ytnova's current directory.\n"
    "# jdupes is non-recursive by default.\n"
    "duplicate report |  | jdupes {} > ytnova-duplicates.txt\n"
    ;
