/* Auto-generated from etc/ytnova.commands for commands.conf starter output. */
static const char default_commands_catalog[] =
    "######################################\n"
    "# commands.conf starter for YtreeNova command customization.\n"
    "#\n"
    "# Only --init and explicit F10 Commands create this file. When the file is\n"
    "# missing, YtreeNova falls back to built-in command defaults without creating\n"
    "# a user copy.\n"
    "#\n"
    "# Canonical columns:\n"
    "#   context | binding | shown | label | action | command\n"
    "#\n"
    "# Rules:\n"
    "# - context is currently dir or file for the visible command-strip actions.\n"
    "# - binding is the real input key (single keys or Ctrl+letter chords).\n"
    "# - shown is the token rendered in footer/help surfaces.\n"
    "# - label is plain user-visible text only; do not encode key markup here.\n"
    "# - action is the stable internal action ID; do not translate or rename it.\n"
    "# - command is blank for built-ins. Use action user-command for custom shell\n"
    "#   commands and put the shell command in the final column.\n"
    "# - Uppercase and lowercase letters may be bound separately.\n"
    "# - Ctrl+letter bindings are case-insensitive, so Ctrl+n and Ctrl+N are the\n"
    "#   same chord.\n"
    "#\n"
    "# Built-in rows below mirror the default visible dir/file command keys. Editing\n"
    "# them lets commands.conf override legacy profile command sections cleanly.\n"
    "######################################\n"
    "# context | binding | shown | label | action | command\n"
    "\n"
    "dir | A | A | Attributes | ACTION_CMD_A |\n"
    "dir | C | C | Copy | ACTION_CMD_C |\n"
    "dir | D | D | Delete | ACTION_CMD_D |\n"
    "dir | F | F | Filter | ACTION_FILTER |\n"
    "dir | G | G | Global | ACTION_CMD_G |\n"
    "dir | I | I | Invert | ACTION_INVERT |\n"
    "dir | J | J | Compare | ACTION_COMPARE_DIR |\n"
    "dir | L | L | Log | ACTION_LOG |\n"
    "dir | M | M | Makedir | ACTION_CMD_M |\n"
    "dir | N | N | Newfile | ACTION_CMD_MKFILE |\n"
    "dir | O | O | Only tagged | ACTION_TOGGLE_TAGGED_MODE |\n"
    "dir | P | P | Pipe | ACTION_CMD_P |\n"
    "dir | Q | Q | Quit | ACTION_QUIT |\n"
    "dir | R | R | Rename | ACTION_CMD_R |\n"
    "dir | S | S | Showall | ACTION_CMD_S |\n"
    "dir | T | T | Tag | ACTION_TAG |\n"
    "dir | U | U | Untag | ACTION_UNTAG |\n"
    "dir | V | V | Movedir | ACTION_CMD_V |\n"
    "dir | W | W | Write | ACTION_CMD_PRINT |\n"
    "dir | X | X | Execute | ACTION_CMD_X |\n"
    "dir | Z | Z | Archive | ACTION_CMD_I |\n"
    "dir | / | / | Jump | ACTION_LIST_JUMP |\n"
    "dir | ` | ` | Dotfiles | ACTION_TOGGLE_HIDDEN |\n"
    "\n"
    "file | A | A | Attributes | ACTION_CMD_A |\n"
    "file | C | C | Copy | ACTION_CMD_C |\n"
    "file | Ctrl+K | ^K | Copy tagged | ACTION_CMD_TAGGED_C |\n"
    "file | D | D | Delete | ACTION_CMD_D |\n"
    "file | E | E | Edit | ACTION_CMD_E |\n"
    "file | F | F | Filter | ACTION_FILTER |\n"
    "file | H | H | Hex | ACTION_CMD_H |\n"
    "file | I | I | Invert | ACTION_INVERT |\n"
    "file | J | J | Compare | ACTION_COMPARE_FILE |\n"
    "file | L | L | Log | ACTION_LOG |\n"
    "file | M | M | Move | ACTION_CMD_M |\n"
    "file | Ctrl+N | ^N | Move tagged | ACTION_CMD_TAGGED_M |\n"
    "file | N | N | Newfile | ACTION_CMD_MKFILE |\n"
    "file | O | O | Only tagged | ACTION_TOGGLE_TAGGED_MODE |\n"
    "file | P | P | Pipe | ACTION_CMD_P |\n"
    "file | Q | Q | Quit | ACTION_QUIT |\n"
    "file | R | R | Rename | ACTION_CMD_R |\n"
    "file | S | S | Sort | ACTION_CMD_S |\n"
    "file | W | W | Write | ACTION_CMD_PRINT |\n"
    "file | X | X | Execute | ACTION_CMD_X |\n"
    "file | Y | Y | Pathcopy | ACTION_CMD_Y |\n"
    "file | Z | Z | Archive | ACTION_CMD_I |\n"
    "file | / | / | Jump | ACTION_LIST_JUMP |\n"
    "file | ` | ` | Dotfiles | ACTION_TOGGLE_HIDDEN |\n"
    "\n"
    "# Example custom shell-command row:\n"
    "# dir | K | K | Disk usage | user-command | du %s | less\n"
    ;
